GET http://localhost:3000/en
Content-Type: application/json


###

GET http://localhost:3000/test2
Content-Type: application/json


###

GET http://localhost:3000/test
Content-Type: application/json

###

POST http://localhost:3000/send
Content-Type: application/json

{
	"userName": "Krzysztof Tomaszewski",
	"email": "drteski@gmail.com",
	"subject": "Moja wiadomość do ciebie",
	"text": "a;lskdjgl;aksjdgldkgfjalsdkjf;laksjd;lfkjas;ldf "
}

